[launcher]
version = 1.0.1
description = Claude Enterprise compliance and analytics data for Splunk.
author = Anthropic Claude Enterprise Add-on Contributors

[id]
version = 1.0.1
name = TA-anthropic_claude_enterprise

[install]
build = 1783616350
is_configured = false
state = enabled

[package]
id = TA-anthropic_claude_enterprise
check_for_updates = false

[ui]
label = Anthropic Claude Enterprise Add-on
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta-anthropic_claude_enterprise_settings = simple
reload.ta-anthropic_claude_enterprise_account = simple
