[anthropic_claude_auth_events]
search = (sourcetype="anthropic:compliance:activity" (event_type="user_signed_in_*" OR event_type="user_signed_out"))

[anthropic_claude_change_events]
search = (sourcetype="anthropic:compliance:activity" (event_type="org_*" OR event_type="project_*" OR event_type="org_data_export_*" OR event_type="conversation_*"))

[anthropic_claude_file_events]
search = (sourcetype="anthropic:compliance:activity" event_type="file_uploaded")

[anthropic_claude_usage_events]
search = (sourcetype="anthropic:analytics:*")
