[anthropic:compliance:activity]
SHOULD_LINEMERGE = false
TRUNCATE = 999999
TIME_PREFIX = "created_at"
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 64
category = Security

[anthropic:compliance:user]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Security

[anthropic:compliance:organization]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Security

[anthropic:compliance:group]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Security

[anthropic:compliance:chat_content]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Security

[anthropic:compliance:file_metadata]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Security

[anthropic:analytics:summary]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:usage]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:cost]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:user_usage]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:user_cost]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:user_activity]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:spend_limit]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application

[anthropic:analytics:spend_limit_request]
SHOULD_LINEMERGE = false
KV_MODE = json
category = Application
